import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Nav/Navbar";
// import Footer from "../../components/Footer/Footer";
import Container from "@mui/material/Container";
import StoreProvider from "../../utils/reduxstore/storeProvider";
// import { Provider } from "react-redux";
// import store from "../../utils/reduxstore/store";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      <body className={poppins.className}>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <Container>
            <main className="flex-grow">{children}</main>
          </Container>

          {/* <Footer /> */}
        </div>
      </body>
      </StoreProvider>
    </html>
  );
}
